version: '3.8'

services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: alissa-school-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-alissa_root_password}
      MYSQL_DATABASE: ${DB_NAME:-alissa_school}
      MYSQL_USER: ${DB_USER:-alissa_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-alissa_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - alissa-network
    command: --default-authentication-plugin=mysql_native_password

  # Cache Redis
  redis:
    image: redis:7-alpine
    container_name: alissa-school-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - alissa-network
    command: redis-server --appendonly yes

  # Backend API
  backend:
    build: .
    container_name: alissa-school-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-alissa_school}
      - DB_USER=${DB_USER:-alissa_user}
      - DB_PASSWORD=${DB_PASSWORD:-alissa_password}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - BASE_URL=${BASE_URL:-http://localhost:3000}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mysql
      - redis
    networks:
      - alissa-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx (reverse proxy)
  nginx:
    image: nginx:alpine
    container_name: alissa-school-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - alissa-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  alissa-network:
    driver: bridge
